/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: (typeof import('ant-design-vue/es'))['Avatar']
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACard: (typeof import('ant-design-vue/es'))['Card']
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox']
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup']
    ACol: (typeof import('ant-design-vue/es'))['Col']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADatePicker: (typeof import('ant-design-vue/es'))['DatePicker']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputPassword: (typeof import('ant-design-vue/es'))['InputPassword']
    ARadio: (typeof import('ant-design-vue/es'))['Radio']
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup']
    ARow: (typeof import('ant-design-vue/es'))['Row']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASelectOption: (typeof import('ant-design-vue/es'))['SelectOption']
    ASwitch: (typeof import('ant-design-vue/es'))['Switch']
    ATabPane: (typeof import('ant-design-vue/es'))['TabPane']
    ATabs: (typeof import('ant-design-vue/es'))['Tabs']
    ATag: (typeof import('ant-design-vue/es'))['Tag']
    ATextarea: (typeof import('ant-design-vue/es'))['Textarea']
    Layout: (typeof import('./src/components/Layout/index.vue'))['default']
    LayoutTab: (typeof import('./src/components/Layout/components/Layout-Tab.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
