/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: (typeof import('ant-design-vue/es'))['Avatar']
    AButton: (typeof import('ant-design-vue/es'))['Button']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputPassword: (typeof import('ant-design-vue/es'))['InputPassword']
    Layout: (typeof import('./src/components/Layout/index.vue'))['default']
    LayoutTab: (typeof import('./src/components/Layout/components/Layout-Tab.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
